version: '3.0'

services:
  nginx:
    image: nginx:1.23.0-alpine
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/conf.d/demos.conf:/etc/nginx/conf.d/demos.conf
      - ./docker/nginx/log:/var/log/nginx
    depends_on:
      - php
    ports:
      - "${NGINX_PORT:-80}:80"

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
      - ./docker/php/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
